debug: Fix typo in raid5_active script
A variable was mistyped and not properly tested causing an exception.

NameError: name 'non_lru_stripse' is not defined